const express = require("express");
const { getMyCompany, createOrUpdateCompany } = require("../controllers/companyController");
const authMiddleware = require("../middleware/authMiddleware");
const requireRole = require("../middleware/roleMiddleware");
const validate = require("../middleware/validate");
const { companySchema } = require("../schemas/companySchema");
const router = express.Router();
router.use(authMiddleware, requireRole("employer"));
router.get("/", getMyCompany);
router.post("/", validate(companySchema), createOrUpdateCompany);
module.exports = router;
