const express = require("express");
const { createJob, getMyJobs, updateJob, deleteJob } = require("../controllers/employerJobController");
const authMiddleware = require("../middleware/authMiddleware");
const requireRole = require("../middleware/roleMiddleware");
const validate = require("../middleware/validate");
const { jobSchema, updateJobSchema } = require("../schemas/jobSchema");
const router = express.Router();
router.use(authMiddleware, requireRole("employer"));
router.get("/", getMyJobs);
router.post("/", validate(jobSchema), createJob);
router.put("/:id", validate(updateJobSchema), updateJob);
router.delete("/:id", deleteJob);
module.exports = router;
