const express = require("express");
const { getApplications, updateStatus } = require("../controllers/employerApplicationController");
const authMiddleware = require("../middleware/authMiddleware");
const requireRole = require("../middleware/roleMiddleware");
const validate = require("../middleware/validate");
const { applicationStatusSchema } = require("../schemas/applicationSchema");
const router = express.Router();
router.use(authMiddleware, requireRole("employer"));
router.get("/", getApplications);
router.patch("/:id/status", validate(applicationStatusSchema), updateStatus);
module.exports = router;
