import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import Navbar from "../../components/Navbar/Navbar";
import Footer from "../../components/Footer/Footer";
import { api } from "../../services/api";
import { useAuth } from "../../context/AuthContext";

const API = (import.meta.env.VITE_API_URL || "http://localhost:5000").replace(/\/$/, "");
const initial = { title:"", description:"", skills:"", location:"", workMode:"onsite", employmentType:"full-time", experience:"", salaryMin:"", salaryMax:"", salaryPeriod:"year", openings:1, deadline:"", status:"pending" };

function PostJob() {
  const { id } = useParams(); const navigate = useNavigate(); const { token, logout } = useAuth(); const [form,setForm]=useState(initial); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
  useEffect(()=>{ if(!token){navigate("/login",{replace:true});return;} if(id){api("/api/employer/jobs").then(d=>{const job=(d.jobs||[]).find(j=>j._id===id);if(!job){setError("Job not found");return;}setForm({...initial,...job,skills:(job.skills||[]).join(", "),deadline:job.deadline?job.deadline.slice(0,10):""})}).catch(e=>{if(String(e.message||"").toLowerCase().includes("authentication")){logout();navigate("/login",{replace:true});}else setError(e.message||"Unable to load job")});}},[id,token,navigate,logout]);
  const set=(key,value)=>setForm({...form,[key]:value});
  const submit=async e=>{e.preventDefault();setLoading(true);setError("");try{const payload={title:form.title.trim(),description:form.description.trim(),skills:form.skills.split(",").map(s=>s.trim()).filter(Boolean),location:form.location.trim(),workMode:form.workMode,employmentType:form.employmentType,experience:form.experience.trim(),salaryMin:form.salaryMin?Number(form.salaryMin):null,salaryMax:form.salaryMax?Number(form.salaryMax):null,salaryPeriod:form.salaryPeriod,openings:Number(form.openings)||1,deadline:form.deadline||null,status:"published"};await api(`/api/employer/jobs${id?`/${id}`:""}`,{method:id?"PUT":"POST",body:JSON.stringify(payload)});navigate("/employer/dashboard")}catch(err){if(String(err.message||"").toLowerCase().includes("authentication")){logout();navigate("/login",{replace:true});}else setError(err.message||"Unable to save job")}finally{setLoading(false)}};
  return <><Navbar/><section className="bg-black px-6 py-12 text-white"><div className="mx-auto max-w-4xl"><p className="text-sm text-gray-400">Employer Portal</p><h1 className="mt-2 text-3xl font-bold">{id?"Edit Job":"Post a New Job"}</h1></div></section><section className="px-6 py-12"><form onSubmit={submit} className="mx-auto max-w-4xl rounded-xl border border-gray-200 bg-white p-8 shadow-sm"><p className="mb-6 text-sm text-gray-500">Publish your hiring opportunity on MeriJob.</p>{error&&<div className="mb-5 rounded-md bg-red-50 px-4 py-3 text-sm text-red-600">{error}</div>}<div className="grid gap-5 md:grid-cols-2">
    <Field label="Job Title" value={form.title} onChange={e=>set("title",e.target.value)} required/><Field label="Location" value={form.location} onChange={e=>set("location",e.target.value)}/><Field label="Skills (comma separated)" value={form.skills} onChange={e=>set("skills",e.target.value)} placeholder="React, Node.js, MongoDB"/><Field label="Experience" value={form.experience} onChange={e=>set("experience",e.target.value)} placeholder="0-2 years"/>
    <Select label="Work Mode" value={form.workMode} onChange={e=>set("workMode",e.target.value)} options={[["onsite","On-site"],["hybrid","Hybrid"],["remote","Remote"]]}/><Select label="Employment Type" value={form.employmentType} onChange={e=>set("employmentType",e.target.value)} options={[["full-time","Full-time"],["part-time","Part-time"],["contract","Contract"],["internship","Internship"],["freelance","Freelance"]]}/><Field label="Minimum Salary (₹)" type="number" value={form.salaryMin} onChange={e=>set("salaryMin",e.target.value)}/><Field label="Maximum Salary (₹)" type="number" value={form.salaryMax} onChange={e=>set("salaryMax",e.target.value)}/><Field label="Openings" type="number" min="1" value={form.openings} onChange={e=>set("openings",e.target.value)}/><Field label="Application Deadline" type="date" value={form.deadline} onChange={e=>set("deadline",e.target.value)}/>
  </div><div className="mt-5"><label className="mb-2 block text-xs font-medium text-gray-700">Job Description</label><textarea required rows="10" value={form.description} onChange={e=>set("description",e.target.value)} placeholder="Describe the role, responsibilities and requirements..." className="w-full rounded-md border border-gray-200 px-4 py-3 text-sm outline-none focus:border-[#309689]"/></div><div className="mt-7 flex justify-end gap-3"><button type="button" onClick={()=>navigate("/employer/dashboard")} className="rounded-md border px-5 py-3 text-xs">Cancel</button><button disabled={loading} className="rounded-md bg-[#309689] px-6 py-3 text-xs font-medium text-white">{loading?"Saving...":id?"Update Job":"Post Job"}</button></div></form></section><Footer/></>;
}
function Field({label,...props}){return <div><label className="mb-2 block text-xs font-medium text-gray-700">{label}</label><input {...props} className="w-full rounded-md border border-gray-200 px-4 py-3 text-sm outline-none focus:border-[#309689]"/></div>}
function Select({label,options,...props}){return <div><label className="mb-2 block text-xs font-medium text-gray-700">{label}</label><select {...props} className="w-full rounded-md border border-gray-200 px-4 py-3 text-sm outline-none focus:border-[#309689]">{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div>}
export default PostJob;
